networks:
  php_pro:
    driver: bridge


volumes:
  database_volume:
    driver: local

services:
  app:
    build:
      context: .docker/php
    restart: always
    ports:
      - "80:80" # http: 80 -> http:localhost:80 https:443
    volumes:
      - .:/var/www/html
    networks:
      - php_pro
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - php_pro
  database:
    image: "mysql:8"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_advanced
    networks:
      - php_pro